"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-10-03 16:00:23.918812
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historical_incidents",
        sa.Column("incident_key", sa.String(length=30), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("unit", sa.String(length=60), nullable=True),
        sa.Column("device", sa.String(length=80), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("affected_service", sa.String(length=60), nullable=True),
        sa.Column("root_cause", sa.Text(), nullable=False),
        sa.Column("root_cause_category", sa.String(length=30), nullable=False),
        sa.Column("pattern", sa.String(length=40), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(384), nullable=True),
        sa.Column("embedding_model", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_historical_incidents_category"),
        "historical_incidents",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_incidents_incident_key"),
        "historical_incidents",
        ["incident_key"],
        unique=True,
    )
    op.create_index(
        op.f("ix_historical_incidents_root_cause_category"),
        "historical_incidents",
        ["root_cause_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_incidents_timestamp"),
        "historical_incidents",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_incidents_unit"),
        "historical_incidents",
        ["unit"],
        unique=False,
    )
    op.create_table(
        "logs",
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("hostname", sa.String(length=80), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("destination", sa.String(length=80), nullable=True),
        sa.Column("service", sa.String(length=60), nullable=True),
        sa.Column("log_level", sa.String(length=10), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("packet_loss", sa.Float(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_logs_event_type"), "logs", ["event_type"], unique=False)
    op.create_index(op.f("ix_logs_hostname"), "logs", ["hostname"], unique=False)
    op.create_index(
        "ix_logs_hostname_ts", "logs", ["hostname", "timestamp"], unique=False
    )
    op.create_index(op.f("ix_logs_log_level"), "logs", ["log_level"], unique=False)
    op.create_index(op.f("ix_logs_service"), "logs", ["service"], unique=False)
    op.create_index("ix_logs_source_ts", "logs", ["source", "timestamp"], unique=False)
    op.create_index(op.f("ix_logs_timestamp"), "logs", ["timestamp"], unique=False)
    op.create_table(
        "servers",
        sa.Column("hostname", sa.String(length=80), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("environment", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("operating_system", sa.String(length=80), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_servers_hostname"), "servers", ["hostname"], unique=True)
    op.create_table(
        "sop_documents",
        sa.Column("doc_code", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("doc_type", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=True),
        sa.Column("source_path", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sop_documents_category"), "sop_documents", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_sop_documents_doc_code"), "sop_documents", ["doc_code"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "devices",
        sa.Column("hostname", sa.String(length=80), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("mac_address", sa.String(length=17), nullable=True),
        sa.Column("unit", sa.String(length=60), nullable=False),
        sa.Column("vlan", sa.Integer(), nullable=True),
        sa.Column("device_type", sa.String(length=30), nullable=False),
        sa.Column("operating_system", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("server_id", sa.Uuid(), nullable=True),
        sa.Column("switch_id", sa.Uuid(), nullable=True),
        sa.Column("switch_port", sa.String(length=20), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["switch_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_devices_device_type"), "devices", ["device_type"], unique=False
    )
    op.create_index(op.f("ix_devices_hostname"), "devices", ["hostname"], unique=True)
    op.create_index(op.f("ix_devices_unit"), "devices", ["unit"], unique=False)
    op.create_table(
        "incidents",
        sa.Column("ticket_number", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reported_by", sa.Uuid(), nullable=True),
        sa.Column("reporter_name", sa.String(length=120), nullable=True),
        sa.Column("affected_unit", sa.String(length=60), nullable=True),
        sa.Column("affected_device", sa.String(length=80), nullable=True),
        sa.Column("affected_service", sa.String(length=60), nullable=True),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("category", sa.String(length=30), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("scenario_id", sa.String(length=10), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reported_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incidents_affected_unit"), "incidents", ["affected_unit"], unique=False
    )
    op.create_index(
        op.f("ix_incidents_category"), "incidents", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_incidents_occurred_at"), "incidents", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_incidents_severity"), "incidents", ["severity"], unique=False
    )
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_index(
        op.f("ix_incidents_ticket_number"), "incidents", ["ticket_number"], unique=True
    )
    op.create_table(
        "services",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("server_id", sa.Uuid(), nullable=True),
        sa.Column("port", sa.Integer(), nullable=True),
        sa.Column("protocol", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("health_endpoint", sa.String(length=255), nullable=True),
        sa.Column("response_time_ms", sa.Float(), nullable=True),
        sa.Column("last_checked", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_services_name"), "services", ["name"], unique=True)
    op.create_table(
        "sop_versions",
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("sop_code", sa.String(length=40), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "sections",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["sop_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("content_hash"),
    )
    op.create_index(
        op.f("ix_sop_versions_document_id"),
        "sop_versions",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sop_versions_effective_date"),
        "sop_versions",
        ["effective_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sop_versions_sop_code"), "sop_versions", ["sop_code"], unique=False
    )
    op.create_table(
        "investigations",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("parent_investigation_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("root_cause_category", sa.String(length=30), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column(
            "stages",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "report",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "audit",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "config_snapshot",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column(
            "input_snapshot",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("model_used", sa.String(length=120), nullable=True),
        sa.Column("ai_mode", sa.String(length=30), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_investigation_id"],
            ["investigations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_investigations_incident_id"),
        "investigations",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigations_root_cause_category"),
        "investigations",
        ["root_cause_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigations_status"), "investigations", ["status"], unique=False
    )
    op.create_table(
        "resolutions",
        sa.Column("incident_id", sa.Uuid(), nullable=True),
        sa.Column("historical_incident_id", sa.Uuid(), nullable=True),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.Column("root_cause_category", sa.String(length=30), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=False),
        sa.Column("resolution_time_minutes", sa.Integer(), nullable=True),
        sa.Column("resolved_by", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["historical_incident_id"],
            ["historical_incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resolutions_historical_incident_id"),
        "resolutions",
        ["historical_incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_resolutions_incident_id"), "resolutions", ["incident_id"], unique=False
    )
    op.create_table(
        "sop_chunks",
        sa.Column("version_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("sop_code", sa.String(length=40), nullable=False),
        sa.Column("section", sa.String(length=40), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(384), nullable=True),
        sa.Column("embedding_model", sa.String(length=120), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["sop_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["sop_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sop_chunks_document_id"), "sop_chunks", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_sop_chunks_sop_code"), "sop_chunks", ["sop_code"], unique=False
    )
    op.create_index(
        op.f("ix_sop_chunks_version_id"), "sop_chunks", ["version_id"], unique=False
    )
    op.create_table(
        "incident_events",
        sa.Column("incident_id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_incident_events_incident_id"),
        "incident_events",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_events_investigation_id"),
        "incident_events",
        ["investigation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_incident_events_timestamp"),
        "incident_events",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "investigation_evidence",
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_key", sa.String(length=12), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=True),
        sa.Column("evidence_text", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("evidence_timestamp", sa.DateTime(), nullable=True),
        sa.Column("temporal_relation", sa.String(length=20), nullable=True),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("temporal_score", sa.Float(), nullable=True),
        sa.Column("confidence_contribution", sa.Float(), nullable=True),
        sa.Column("priority_rank", sa.Integer(), nullable=False),
        sa.Column(
            "tags",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "hypothesis_ids",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_investigation_evidence_investigation_id"),
        "investigation_evidence",
        ["investigation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigation_evidence_source_type"),
        "investigation_evidence",
        ["source_type"],
        unique=False,
    )
    op.create_table(
        "tool_executions",
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("tool_name", sa.String(length=60), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column(
            "arguments",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("execution_time", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tool_executions_investigation_id"),
        "tool_executions",
        ["investigation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tool_executions_tool_name"),
        "tool_executions",
        ["tool_name"],
        unique=False,
    )
    # ### end Alembic commands ###

    for _table in ("sop_chunks", "historical_incidents"):
        op.execute(
            f"CREATE INDEX IF NOT EXISTS ix_{_table}_embedding_hnsw ON {_table} USING hnsw (embedding vector_cosine_ops)"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_executions_tool_name"), table_name="tool_executions")
    op.drop_index(
        op.f("ix_tool_executions_investigation_id"), table_name="tool_executions"
    )
    op.drop_table("tool_executions")
    op.drop_index(
        op.f("ix_investigation_evidence_source_type"),
        table_name="investigation_evidence",
    )
    op.drop_index(
        op.f("ix_investigation_evidence_investigation_id"),
        table_name="investigation_evidence",
    )
    op.drop_table("investigation_evidence")
    op.drop_index(op.f("ix_incident_events_timestamp"), table_name="incident_events")
    op.drop_index(
        op.f("ix_incident_events_investigation_id"), table_name="incident_events"
    )
    op.drop_index(op.f("ix_incident_events_incident_id"), table_name="incident_events")
    op.drop_table("incident_events")
    op.drop_index(op.f("ix_sop_chunks_version_id"), table_name="sop_chunks")
    op.drop_index(op.f("ix_sop_chunks_sop_code"), table_name="sop_chunks")
    op.drop_index(op.f("ix_sop_chunks_document_id"), table_name="sop_chunks")
    op.drop_table("sop_chunks")
    op.drop_index(op.f("ix_resolutions_incident_id"), table_name="resolutions")
    op.drop_index(
        op.f("ix_resolutions_historical_incident_id"), table_name="resolutions"
    )
    op.drop_table("resolutions")
    op.drop_index(op.f("ix_investigations_status"), table_name="investigations")
    op.drop_index(
        op.f("ix_investigations_root_cause_category"), table_name="investigations"
    )
    op.drop_index(op.f("ix_investigations_incident_id"), table_name="investigations")
    op.drop_table("investigations")
    op.drop_index(op.f("ix_sop_versions_sop_code"), table_name="sop_versions")
    op.drop_index(op.f("ix_sop_versions_effective_date"), table_name="sop_versions")
    op.drop_index(op.f("ix_sop_versions_document_id"), table_name="sop_versions")
    op.drop_table("sop_versions")
    op.drop_index(op.f("ix_services_name"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_incidents_ticket_number"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_severity"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_occurred_at"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_category"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_affected_unit"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_devices_unit"), table_name="devices")
    op.drop_index(op.f("ix_devices_hostname"), table_name="devices")
    op.drop_index(op.f("ix_devices_device_type"), table_name="devices")
    op.drop_table("devices")
    op.drop_table("users")
    op.drop_index(op.f("ix_sop_documents_doc_code"), table_name="sop_documents")
    op.drop_index(op.f("ix_sop_documents_category"), table_name="sop_documents")
    op.drop_table("sop_documents")
    op.drop_index(op.f("ix_servers_hostname"), table_name="servers")
    op.drop_table("servers")
    op.drop_index(op.f("ix_logs_timestamp"), table_name="logs")
    op.drop_index("ix_logs_source_ts", table_name="logs")
    op.drop_index(op.f("ix_logs_service"), table_name="logs")
    op.drop_index(op.f("ix_logs_log_level"), table_name="logs")
    op.drop_index("ix_logs_hostname_ts", table_name="logs")
    op.drop_index(op.f("ix_logs_hostname"), table_name="logs")
    op.drop_index(op.f("ix_logs_event_type"), table_name="logs")
    op.drop_table("logs")
    op.drop_index(
        op.f("ix_historical_incidents_unit"), table_name="historical_incidents"
    )
    op.drop_index(
        op.f("ix_historical_incidents_timestamp"), table_name="historical_incidents"
    )
    op.drop_index(
        op.f("ix_historical_incidents_root_cause_category"),
        table_name="historical_incidents",
    )
    op.drop_index(
        op.f("ix_historical_incidents_incident_key"), table_name="historical_incidents"
    )
    op.drop_index(
        op.f("ix_historical_incidents_category"), table_name="historical_incidents"
    )
    op.drop_table("historical_incidents")
    # ### end Alembic commands ###
