import { api, post } from '@/services/api'
import type {
  AiConfig, AuditEvent, BenchmarkResult, CompareResult, DashboardStats, IncidentScenario, Device, EvidenceRow, Health, Historical, Incident, IncidentCreate, Investigation, InvestigationAnalytics,
  AuthUser, InvestigationBrief, LogFilters, LogRow, Metric, Page, Server, ServiceState, Sop, Topology, ToolExecution, TimelineItem,
} from '@/types/api'

type P = Record<string, string | number | boolean | undefined | null>

export const endpoints = {
  me: () => api<AuthUser>('/api/auth/me'),
  login: (body: { email: string; password: string }) => post<AuthUser>('/api/auth/login', body),
  register: (body: { name: string; email: string; password: string }) => post<AuthUser>('/api/auth/register', body),
  logout: () => api<null>('/api/auth/logout', { method: 'POST' }),
  health: () => api<Health>('/api/health'),
  dashboard: () => api<DashboardStats>('/api/dashboard/stats'),
  scenarios: () => api<IncidentScenario[]>('/api/scenarios'),
  incidents: (params: P) => api<Page<Incident>>('/api/incidents', { params }),
  incident: (id: string) => api<Incident>(`/api/incidents/${id}`),
  createIncident: (body: IncidentCreate) => post<Incident>('/api/incidents', body),
  resolveIncident: (id: string, body: { resolution: string; root_cause?: string }) => post<Incident>(`/api/incidents/${id}/resolve`, body),
  incidentInvestigations: (id: string) => api<InvestigationBrief[]>(`/api/incidents/${id}/investigations`),
  incidentEvents: (id: string) => api<AuditEvent[]>(`/api/incidents/${id}/events`),
  investigate: (id: string) => post<InvestigationBrief>(`/api/incidents/${id}/investigate`),
  investigations: (params: P) => api<Page<InvestigationBrief>>('/api/investigations', { params }),
  investigation: (id: string) => api<Investigation>(`/api/investigations/${id}`),
  timeline: (id: string) => api<{ events: AuditEvent[]; evidence_timeline: TimelineItem[] }>(`/api/investigations/${id}/timeline`),
  evidence: (id: string, params: P) => api<EvidenceRow[]>(`/api/investigations/${id}/evidence`, { params }),
  tools: (id: string) => api<ToolExecution[]>(`/api/investigations/${id}/tools`),
  replay: (id: string) => post<InvestigationBrief>(`/api/investigations/${id}/replay`),
  compare: (a: string, b: string) => api<CompareResult>(`/api/investigations/${a}/compare/${b}`),
  devices: (params: P) => api<Page<Device>>('/api/devices', { params }),
  deviceFilters: () => api<{ units: string[]; device_types: string[] }>('/api/devices/filters'),
  servers: (params: P) => api<Server[]>('/api/servers', { params }),
  serverMetrics: (host: string, params: P) => api<Metric[]>(`/api/servers/${host}/metrics`, { params }),
  services: (params: P) => api<ServiceState[]>('/api/services', { params }),
  serviceHistory: (name: string, params: P) => api<{ timestamp: string; status: string; response_time_ms: number }[]>(`/api/services/${encodeURIComponent(name)}/history`, { params }),
  topology: () => api<Topology>('/api/topology'),
  logs: (params: P) => api<Page<LogRow>>('/api/logs', { params }),
  logFilters: () => api<LogFilters>('/api/logs/filters'),
  correlated: (id: string) => api<{ incident_time: string; patterns: { name: string; correlation_score: number; order_ok: boolean; lag_seconds: number; cause_domain: string }[]; events: TimelineItem[] }>('/api/logs/correlated', { params: { investigation_id: id } }),
  sops: (params: P) => api<Sop[]>('/api/sops', { params }),
  historical: (params: P) => api<Page<Historical>>('/api/historical-incidents', { params }),
  aiConfig: () => api<AiConfig>('/api/ai/config'),
  testLlm: () => post<{ ok: boolean; message: string }>('/api/ai/test/llm'),
  testMcp: () => post<{ ok: boolean; message: string }>('/api/ai/test/mcp'),
  benchmark: () => api<BenchmarkResult>('/api/analytics/benchmark'),
  runBenchmark: () => post<{ status: string }>('/api/analytics/benchmark/run'),
  investigationAnalytics: () => api<InvestigationAnalytics>('/api/analytics/investigations'),
}
